name: "Organization workflow action"
description: "Action to register organization workflow"
branding:
    icon: "check-circle"
    color: "white"
inputs:
    id:
        description: "ID of run (provided by GitHub app via `github.event.clientPayload.id`)"
        required: true
    runId:
        description: "ID of workflow run (provided via GitHub syntax `github.runId`)"
        required: true
    name:
        description: "Name of check (Use `github.workflow` to use the name of the workflow)"
        required: true
    callbackUrl:
        description: "Callback url for register call (provided by GitHub app via `github.event.clientPayload.callbackUrl`)"
        required: true
    sha:
        description: "Sha of original commit (provided by GitHub app via `github.event.clientPayload.sha`)"
        required: true
    enforce:
        description: "Enforce [required status check](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/enabling-required-status-checks)"
        required: false
        default: false
    enforceAdmin:
        description: "Enforce [required status check](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/enabling-required-status-checks) for admins"
        required: false
        default: false
    documentation:
        description: "Link to documentation of this check. This is shown with the status check on the original commit. (eg `.github/workflows/compliance-info.md`)"
        required: false
runs:
    using: "composite"
    steps:
        - run: |
              curl -G \
                "${{ inputs.callbackUrl }}" \
                -d id=${{ inputs.id }} \
                -d runId=${{ inputs.runId }} \
                -d sha=${{ inputs.sha }} \
                -d enforce=${{ inputs.enforce }} \
                -d enforceAdmin=${{ inputs.enforceAdmin }} \
                --data-urlencode "name=${{ env.name || github.workflow }}" \
                --data-urlencode "documentation=${{ inputs.documentation }}"
          shell: bash
